openai_api_key: sk-5xoPNLSOEEsWgy37Aa3dFa00335746A0Ac3d3e527aEc24B8

tmdb_access_token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NGRjMzhmYTQxY2EyNzE5NjA2MTU3YzBlZGVhODQzNyIsInN1YiI6IjY1MGYwNjYxM2E0YTEyMDEzOTU1NjdmMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.y4XMqNFw52BXgiwzFV_WqhvWCpXrdZjjuDBMwl5lWns

spotipy_client_id: tmp
spotipy_client_secret: tmp 
spotipy_redirect_uri: tmp
